version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: sanaz1080
      MYSQL_DATABASE: issue_tracker
      MYSQL_USER: sanaz
      MYSQL_PASSWORD: sanaz1080
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
